#ifndef PLATFORM_MEMORY_MAP_H
#define PLATFORM_MEMORY_MAP_H

#define PLATFORM_QSPI_MAPPED_BASE     0x90000000UL
#define PLATFORM_QSPI_MAPPED_SIZE     (32UL * 1024UL * 1024UL)
#define PLATFORM_APP_VECTOR_ALIGNMENT 128UL

#define PLATFORM_INTERNAL_FLASH_BASE  0x08000000UL
#define PLATFORM_INTERNAL_FLASH_SIZE  (2UL * 1024UL * 1024UL)
#define PLATFORM_BOOTLOADER_SIZE      (256UL * 1024UL)
#define PLATFORM_JOURNAL_SLOT_SIZE    (128UL * 1024UL)
#define PLATFORM_JOURNAL_SLOT_COUNT   2U
#define PLATFORM_JOURNAL_SIZE         (PLATFORM_JOURNAL_SLOT_SIZE * PLATFORM_JOURNAL_SLOT_COUNT)
#define PLATFORM_APPLICATION_ADDRESS  (PLATFORM_INTERNAL_FLASH_BASE + \
                                       PLATFORM_BOOTLOADER_SIZE)
#define PLATFORM_APPLICATION_SIZE     (PLATFORM_INTERNAL_FLASH_SIZE - \
                                       PLATFORM_BOOTLOADER_SIZE - PLATFORM_JOURNAL_SIZE)
#define PLATFORM_JOURNAL_ADDRESS      (PLATFORM_INTERNAL_FLASH_BASE + \
                                       PLATFORM_INTERNAL_FLASH_SIZE - PLATFORM_JOURNAL_SIZE)

/* The internal application window is reserved for a future image; the current APP is in QSPI. */

#if (PLATFORM_BOOTLOADER_SIZE + PLATFORM_JOURNAL_SIZE) > PLATFORM_INTERNAL_FLASH_SIZE
#error "Internal flash layout does not fit"
#endif

#define PLATFORM_APP_OFFSET      0UL
#define PLATFORM_APP_MAX_SIZE    (1UL * 1024UL * 1024UL)
#define PLATFORM_GUI_OFFSET      PLATFORM_APP_MAX_SIZE
#define PLATFORM_GUI_MAX_SIZE    (24UL * 1024UL * 1024UL)
#define PLATFORM_VOICE_OFFSET    (PLATFORM_GUI_OFFSET + PLATFORM_GUI_MAX_SIZE)
#define PLATFORM_VOICE_MAX_SIZE  (6UL * 1024UL * 1024UL)
#define PLATFORM_CONFIG_OFFSET   (PLATFORM_VOICE_OFFSET + PLATFORM_VOICE_MAX_SIZE)
#define PLATFORM_CONFIG_MAX_SIZE (1UL * 1024UL * 1024UL)
#if PLATFORM_CONFIG_MAX_SIZE + PLATFORM_CONFIG_OFFSET != PLATFORM_QSPI_MAPPED_SIZE
#error "QSPI partitions must cover the 32 MiB device exactly"
#endif
#define PLATFORM_THERAPY_TARGET_ADDRESS 0x08000000UL
#define PLATFORM_THERAPY_MAX_SIZE       (2UL * 1024UL * 1024UL)

#define PLATFORM_DTCM_BASE     0x20000000UL
#define PLATFORM_DTCM_END      0x20020000UL
#define PLATFORM_AXI_SRAM_BASE 0x24000000UL
#define PLATFORM_AXI_SRAM_END  0x24080000UL
#define PLATFORM_D2_SRAM_BASE  0x30000000UL
#define PLATFORM_D2_SRAM_END   0x30048000UL
#define PLATFORM_SRAM4_BASE    0x38000000UL
#define PLATFORM_SRAM4_END     0x38010000UL

#endif /* PLATFORM_MEMORY_MAP_H */
