#!/usr/bin/env python3
"""Build a fixed-runtime APP/GUI release package from an Application ELF."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from elf_image import PackageToolError, read_load_segments
from package_builder import (
    assemble_images,
    create_development_request,
    parse_release_version,
    verify_package_root,
    write_release_package,
)


def build_command(args: argparse.Namespace) -> None:
    release_version = parse_release_version(args.version, "--version")
    minimum_bootloader = parse_release_version(
        args.minimum_bootloader, "--minimum-bootloader"
    )
    images = assemble_images(read_load_segments(args.elf))
    firmware = write_release_package(
        args.output,
        images,
        args.package_id,
        release_version,
        args.build_number,
        minimum_bootloader,
    )
    print(
        json.dumps(
            {
                "firmware": str(firmware),
                "app_bytes": len(images.app),
                "gui_bytes": len(images.gui),
                "request_generated": False,
            },
            indent=2,
        )
    )


def verify_command(args: argparse.Namespace) -> None:
    manifest, _ = verify_package_root(args.package_root)
    print(json.dumps({"package_id": manifest["package_id"], "verified": True}, indent=2))


def create_development_request_command(args: argparse.Namespace) -> None:
    request_path = create_development_request(args.package_root)
    print("DEVELOPMENT TRUST OVERRIDE:")
    print("boot_update_request.json was generated by the host tool.")
    print("This does not represent production release authentication.")
    print(json.dumps({"request": str(request_path)}, indent=2))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    build = subparsers.add_parser("build", help="build firmware/ from an Application ELF")
    build.add_argument("--elf", type=Path, required=True)
    build.add_argument("--output", type=Path, required=True)
    build.add_argument("--package-id", required=True)
    build.add_argument("--version", required=True)
    build.add_argument("--build-number", type=int, required=True)
    build.add_argument("--minimum-bootloader", required=True)
    build.set_defaults(function=build_command)

    verify = subparsers.add_parser("verify", help="verify an existing firmware package")
    verify.add_argument("--package-root", type=Path, required=True)
    verify.set_defaults(function=verify_command)

    development_request = subparsers.add_parser(
        "create-dev-request", help="create a development-only trusted request"
    )
    development_request.add_argument("--package-root", type=Path, required=True)
    development_request.set_defaults(function=create_development_request_command)

    args = parser.parse_args()
    args.function(args)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except PackageToolError as error:
        print(f"error: {error}")
        raise SystemExit(2)
