#ifndef FIRMWARE_UPDATE_TYPES_H
#define FIRMWARE_UPDATE_TYPES_H

#include "firmware/status.h"

#ifdef __cplusplus
extern "C"
{
#endif

    typedef enum
    {
        UPDATE_TARGET_APP = 0,
        UPDATE_TARGET_GUI,
        UPDATE_TARGET_THERAPY,
        UPDATE_TARGET_VOICE,
        UPDATE_TARGET_CONFIG,
        UPDATE_TARGET_RESOURCE
    } update_target_t;

    /* Kept as an alias for existing callers while Services uses update_target_t. */
    typedef update_target_t image_target_t;

#define IMAGE_TARGET_APP      UPDATE_TARGET_APP
#define IMAGE_TARGET_GUI      UPDATE_TARGET_GUI
#define IMAGE_TARGET_THERAPY  UPDATE_TARGET_THERAPY
#define IMAGE_TARGET_VOICE    UPDATE_TARGET_VOICE
#define IMAGE_TARGET_CONFIG   UPDATE_TARGET_CONFIG
#define IMAGE_TARGET_RESOURCE UPDATE_TARGET_RESOURCE

    typedef enum
    {
        UPDATE_OUTCOME_NO_CHANGE = 0,
        UPDATE_OUTCOME_INSTALLED,
        UPDATE_OUTCOME_RECOVERED,
        UPDATE_OUTCOME_RUNTIME_UNSAFE,
        UPDATE_OUTCOME_RESET,
        UPDATE_OUTCOME_LAUNCH
    } update_outcome_t;

#define UPDATE_RESULT_JUMP_APP UPDATE_OUTCOME_LAUNCH
#define UPDATE_RESULT_RESET    UPDATE_OUTCOME_RESET
#define UPDATE_RESULT_WAIT     UPDATE_OUTCOME_NO_CHANGE
#define UPDATE_RESULT_FAILED   UPDATE_OUTCOME_RUNTIME_UNSAFE

    typedef enum
    {
        UPDATE_FAILURE_NONE = 0,
        UPDATE_FAILURE_JOURNAL,
        UPDATE_FAILURE_STORAGE,
        UPDATE_FAILURE_MANIFEST_READ,
        UPDATE_FAILURE_MANIFEST_DIGEST,
        UPDATE_FAILURE_MANIFEST_PARSE,
        UPDATE_FAILURE_REQUEST_PARSE,
        UPDATE_FAILURE_REQUEST_PACKAGE_ID_MISMATCH,
        UPDATE_FAILURE_REQUEST_MANIFEST_DIGEST_MISMATCH,
        UPDATE_FAILURE_REQUEST_COMPONENT_MASK_MISMATCH,
        UPDATE_FAILURE_REQUEST_NOT_ACTIVE,
        UPDATE_FAILURE_SIGNATURE,
        UPDATE_FAILURE_TARGET,
        UPDATE_FAILURE_VERSION,
        UPDATE_FAILURE_FILE_SET,
        UPDATE_FAILURE_INSTALL_SOURCE,
        UPDATE_FAILURE_INSTALL_SIZE,
        UPDATE_FAILURE_INSTALL_ERASE,
        UPDATE_FAILURE_INSTALL_WRITE,
        UPDATE_FAILURE_INSTALL_READBACK,
        UPDATE_FAILURE_INSTALL_HASH,
        UPDATE_FAILURE_INSTALL_CLOSE,
        UPDATE_FAILURE_THERAPY_EXIT,
        UPDATE_FAILURE_CURRENT_VERIFY,
        UPDATE_FAILURE_CURRENT_COMMIT,
        UPDATE_FAILURE_CURRENT_RECONCILE,
        UPDATE_FAILURE_RECOVERY,
        UPDATE_FAILURE_RUNTIME_VECTOR,
        UPDATE_FAILURE_TRIAL_UNCONFIRMED,
        UPDATE_FAILURE_ROLLBACK_INSTALL,
        UPDATE_FAILURE_ROLLBACK_RUNTIME,
        UPDATE_FAILURE_COMMIT_RETRY
    } update_failure_t;

    /* Protocol-level names retained as aliases for the compact result enum. */
#define UPDATE_FAILURE_JOURNAL_INVALID             UPDATE_FAILURE_JOURNAL
#define UPDATE_FAILURE_JOURNAL_READ_FAILED         UPDATE_FAILURE_JOURNAL
#define UPDATE_FAILURE_JOURNAL_WRITE_FAILED        UPDATE_FAILURE_JOURNAL
#define UPDATE_FAILURE_REQUEST_NOT_FOUND           UPDATE_FAILURE_REQUEST_NOT_ACTIVE
#define UPDATE_FAILURE_REQUEST_READ_FAILED         UPDATE_FAILURE_REQUEST_PARSE
#define UPDATE_FAILURE_REQUEST_VERSION_UNSUPPORTED UPDATE_FAILURE_REQUEST_PARSE
#define UPDATE_FAILURE_STORAGE_MOUNT_FAILED        UPDATE_FAILURE_STORAGE
#define UPDATE_FAILURE_MANIFEST_POLICY_FAILED      UPDATE_FAILURE_MANIFEST_PARSE
#define UPDATE_FAILURE_COMPONENT_UNSUPPORTED       UPDATE_FAILURE_TARGET
#define UPDATE_FAILURE_COMPONENT_SIZE_MISMATCH     UPDATE_FAILURE_INSTALL_SIZE
#define UPDATE_FAILURE_COMPONENT_HASH_MISMATCH     UPDATE_FAILURE_INSTALL_HASH
#define UPDATE_FAILURE_TARGET_RANGE_INVALID        UPDATE_FAILURE_TARGET
#define UPDATE_FAILURE_ERASE_FAILED                UPDATE_FAILURE_INSTALL_ERASE
#define UPDATE_FAILURE_WRITE_FAILED                UPDATE_FAILURE_INSTALL_WRITE
#define UPDATE_FAILURE_READBACK_FAILED             UPDATE_FAILURE_INSTALL_READBACK
#define UPDATE_FAILURE_THERAPY_PROGRAM_FAILED      UPDATE_FAILURE_THERAPY_EXIT

    typedef struct
    {
        update_outcome_t outcome;
        update_failure_t failure;
        firmware_status_t status;
    } update_result_t;

#ifdef __cplusplus
}
#endif

#endif
