#include "boot_error.h"

const char *Boot_ErrorToString(BootError error)
{
  switch (error)
  {
    case BOOT_ERR_NONE:
      return "none";
    case BOOT_ERR_INVALID_ARGUMENT:
      return "invalid_argument";
    case BOOT_ERR_NOT_IMPLEMENTED:
      return "not_implemented";
    case BOOT_ERR_CTRL_NOT_FOUND:
      return "ctrl_not_found";
    case BOOT_ERR_CTRL_CRC:
      return "ctrl_crc";
    case BOOT_ERR_USB_NOT_DETECTED:
      return "usb_not_detected";
    case BOOT_ERR_FS_MOUNT:
      return "fs_mount";
    case BOOT_ERR_UPGRADE_DIR_MISSING:
      return "upgrade_dir_missing";
    case BOOT_ERR_MANIFEST_NOT_FOUND:
      return "manifest_not_found";
    case BOOT_ERR_MANIFEST_PARSE:
      return "manifest_parse";
    case BOOT_ERR_FILE_MISSING:
      return "file_missing";
    case BOOT_ERR_FILE_SIZE:
      return "file_size";
    case BOOT_ERR_FILE_CRC:
      return "file_crc";
    case BOOT_ERR_FILE_WRITE:
      return "file_write";
    case BOOT_ERR_PRODUCT_MISMATCH:
      return "product_mismatch";
    case BOOT_ERR_BOARD_MISMATCH:
      return "board_mismatch";
    case BOOT_ERR_SERIAL_MISMATCH:
      return "serial_mismatch";
    case BOOT_ERR_VERSION_POLICY:
      return "version_policy";
    case BOOT_ERR_FLASH_ERASE:
      return "flash_erase";
    case BOOT_ERR_FLASH_WRITE:
      return "flash_write";
    case BOOT_ERR_FLASH_VERIFY:
      return "flash_verify";
    case BOOT_ERR_FLASH_RANGE:
      return "flash_range";
    case BOOT_ERR_IMAGE_HEADER:
      return "image_header";
    case BOOT_ERR_IMAGE_TYPE:
      return "image_type";
    case BOOT_ERR_IMAGE_SLOT:
      return "image_slot";
    case BOOT_ERR_IMAGE_SIZE:
      return "image_size";
    case BOOT_ERR_IMAGE_VECTOR:
      return "image_vector";
    case BOOT_ERR_IMAGE_CRC:
      return "image_crc";
    case BOOT_ERR_EXTFLASH_ERASE:
      return "extflash_erase";
    case BOOT_ERR_EXTFLASH_WRITE:
      return "extflash_write";
    case BOOT_ERR_EXTFLASH_READ:
      return "extflash_read";
    case BOOT_ERR_EXTFLASH_DUMP:
      return "extflash_dump";
    case BOOT_ERR_EXTFLASH_RANGE:
      return "extflash_range";
    case BOOT_ERR_CTRL_CORRUPTED:
      return "ctrl_corrupted";
    case BOOT_ERR_NO_BOOTABLE_IMAGE:
      return "no_bootable_image";
    case BOOT_ERR_PENDING_SLOT_EXHAUSTED:
      return "pending_slot_exhausted";
    case BOOT_ERR_ROLLBACK_FAILED:
      return "rollback_failed";
    case BOOT_ERR_JUMP_FAILED:
      return "jump_failed";
    default:
      return "unknown";
  }
}
