#ifndef FIRMWARE_DISPLAY_LAYOUT_H
#define FIRMWARE_DISPLAY_LAYOUT_H

/* Display contract shared by the LCD peripheral setup and TouchGFX HAL. */
#define FIRMWARE_DISPLAY_WIDTH_PIXELS       800UL
#define FIRMWARE_DISPLAY_HEIGHT_PIXELS      480UL
#define FIRMWARE_DISPLAY_PIXEL_BYTES        4UL
#define FIRMWARE_DISPLAY_FRAMEBUFFER_STRIDE 0x00180000UL
#define FIRMWARE_DISPLAY_FRAMEBUFFER_REGION 0x00400000UL
#define FIRMWARE_DISPLAY_FRAMEBUFFER0       0xC0000000UL
#define FIRMWARE_DISPLAY_FRAMEBUFFER1       0xC0180000UL

#endif
