#ifndef FIRMWARE_PRODUCT_IDENTITY_H
#define FIRMWARE_PRODUCT_IDENTITY_H

#define FIRMWARE_PRODUCT_NAME  "HMI"
#define FIRMWARE_HARDWARE_NAME "STM32H743-W25Q256"

#define FIRMWARE_BOOTLOADER_VERSION_MAJOR 1U
#define FIRMWARE_BOOTLOADER_VERSION_MINOR 0U
#define FIRMWARE_BOOTLOADER_VERSION_PATCH 0U

#endif /* FIRMWARE_PRODUCT_IDENTITY_H */
