/**
 * @file composition_config.h
 * @brief Product-level constants used while building the dependency graph.
 */
#ifndef COMPOSITION_CONFIG_H
#define COMPOSITION_CONFIG_H

#include "services/common/update_request_types.h"

#define COMPOSITION_SECONDARY_MCU_TARGET_F429 1U
#define COMPOSITION_SECONDARY_MCU_TARGET_F030 2U

#ifndef COMPOSITION_SECONDARY_MCU_TARGET
#define COMPOSITION_SECONDARY_MCU_TARGET COMPOSITION_SECONDARY_MCU_TARGET_F030
#endif

/* Each ROM transaction is at most 256 bytes; keep both buffers cache aligned. */
#define COMPOSITION_SECONDARY_MCU_IO_BUFFER_SIZE 256U
#define COMPOSITION_THERAPY_TARGET_ADDRESS       0x08000000UL
#define COMPOSITION_THERAPY_ERASE_PAGE_START     0U

#if COMPOSITION_SECONDARY_MCU_TARGET == COMPOSITION_SECONDARY_MCU_TARGET_F429

/* STM32F429: ID 0x419, sectors 0..7 cover the first 512 KiB. */
#define COMPOSITION_SECONDARY_MCU_DEVICE_ID          0x0419U
#define COMPOSITION_SECONDARY_MCU_USE_EXTENDED_ERASE 1
#define COMPOSITION_THERAPY_TARGET_CAPACITY          (512UL * 1024UL)
#define COMPOSITION_THERAPY_ERASE_PAGE_COUNT         8U

#elif COMPOSITION_SECONDARY_MCU_TARGET == COMPOSITION_SECONDARY_MCU_TARGET_F030

/* STM32F030C8: ID 0x440, 64 pages of 1 KiB. */
#define COMPOSITION_SECONDARY_MCU_DEVICE_ID          0x0440U
#define COMPOSITION_SECONDARY_MCU_USE_EXTENDED_ERASE 1
#define COMPOSITION_THERAPY_TARGET_CAPACITY          (64UL * 1024UL)
#define COMPOSITION_THERAPY_ERASE_PAGE_COUNT         64U

#else
#error "Unsupported COMPOSITION_SECONDARY_MCU_TARGET"
#endif

#if (COMPOSITION_SECONDARY_MCU_DEVICE_ID > 0xFFFFU) ||                                             \
    (COMPOSITION_SECONDARY_MCU_DEVICE_ID == 0xFFFFU)
#error "COMPOSITION_SECONDARY_MCU_DEVICE_ID must be a confirmed 16-bit STM32 ID"
#endif

#if (COMPOSITION_SECONDARY_MCU_USE_EXTENDED_ERASE != 0) &&                                         \
    (COMPOSITION_SECONDARY_MCU_USE_EXTENDED_ERASE != 1)
#error "COMPOSITION_SECONDARY_MCU_USE_EXTENDED_ERASE must be 0 or 1"
#endif

#if (COMPOSITION_THERAPY_TARGET_CAPACITY == 0U) ||                                                 \
    (COMPOSITION_THERAPY_TARGET_CAPACITY > UPDATE_THERAPY_IMAGE_MAX_SIZE) ||                       \
    (COMPOSITION_THERAPY_ERASE_PAGE_COUNT == 0U)
#error "Therapy target layout exceeds the supported package contract"
#endif

#endif
