#ifndef BSP_MEMORY_MAP_H
#define BSP_MEMORY_MAP_H

#include "firmware/display_layout.h"

#define BSP_SDRAM_BASE_ADDRESS 0xC0000000UL
#define BSP_SDRAM_SIZE_BYTES   0x02000000UL

#define BSP_FRAMEBUFFER_WIDTH_PIXELS      800UL
#define BSP_FRAMEBUFFER_HEIGHT_PIXELS     480UL
#define BSP_FRAMEBUFFER_PIXEL_BYTES       4UL
#define BSP_FRAMEBUFFER_STRIDE_BYTES      0x00180000UL
#define BSP_FRAMEBUFFER_REGION_SIZE_BYTES 0x00400000UL
#define BSP_FRAMEBUFFER0_ADDRESS          0xC0000000UL
#define BSP_FRAMEBUFFER1_ADDRESS          0xC0180000UL

#if BSP_FRAMEBUFFER_WIDTH_PIXELS != FIRMWARE_DISPLAY_WIDTH_PIXELS ||                               \
    BSP_FRAMEBUFFER_HEIGHT_PIXELS != FIRMWARE_DISPLAY_HEIGHT_PIXELS ||                             \
    BSP_FRAMEBUFFER_STRIDE_BYTES != FIRMWARE_DISPLAY_FRAMEBUFFER_STRIDE ||                         \
    BSP_FRAMEBUFFER0_ADDRESS != FIRMWARE_DISPLAY_FRAMEBUFFER0 ||                                   \
    BSP_FRAMEBUFFER1_ADDRESS != FIRMWARE_DISPLAY_FRAMEBUFFER1
#error "BSP and shared display layout definitions differ"
#endif

#define BSP_SDRAM_APP_ADDRESS    0xC0400000UL
#define BSP_SDRAM_APP_SIZE_BYTES 0x01C00000UL
#define BSP_LVGL_HEAP_ADDRESS    0xC0400000UL
#define BSP_LVGL_HEAP_SIZE_BYTES 0x00100000UL

#endif
